### ISSUE TITLE
Match error when trying to reproduce a failing test case built with `TrialsApi.uniqueIds`.

### ISSUE THREAD

**Issue by sageserpent-open** [sageserpent-open/americium#71]
The test support code in the Kinetic Merge repository: [MergeTest.simpleMergeTestCases](https://github.com/sageserpent-open/kineticMerge/blob/65318cdeaaa26ab9467bea7dc61865a14f665641/src/test/scala/com/sageserpent/kineticmerge/core/MergeTest.scala#L296) uses `trialsApi.uniqueIds`.

Trying to reproduce the maximally shrunk failing test case from `MergeTest.fullMerge` at that Git commit (SHA 65318cdeaaa26ab9467bea7dc61865a14f665641) results in a `MatchError` in Americium.

```
scala.MatchError: UniqueId (of class com.sageserpent.americium.generation.UniqueId$)

	at com.sageserpent.americium.TrialsImplementation$$anon$1.apply(TrialsImplementation.scala:103)
	at com.sageserpent.americium.TrialsImplementation$$anon$1.apply(TrialsImplementation.scala:64)
```

Seen in Americium **1.17.0**.

**Comment by sageserpent-open** [comment]
A cursory look at the two interpreters shows that the one in `SupplyToSyntaxSkeletalImplementation` (used to generate test cases for a nomal run) has a pattern match for `UniqueId`, whereas the one in `TrialsImplementation` (used for test case reproduction) does not - clearly an oversight and lack of testing.

The job is to add an example to the existing Scalatest test for test case reproduction, confirm that it fails and then add the missing patter match to the second interpreter.

**Comment by sageserpent-open** [comment]
Done, went out in release 1.18.2, Git commit SHA 53d0ee18eba90b471d351980cc357a143b9ec411.

**Comment by sageserpent-open** [comment]
Drat - forgot to increment the unique id when it is read. Need to bolster the test and do another fix and release cycle, grrr...

**Comment by sageserpent-open** [comment]
Another minor release: 1.18.3, Git commit SHA fd6cf1f598a90a67c1ec21fe1cd8f80a0e945860.

**Comment by sageserpent-open** [comment]
Confirmed that the test in the Kinetic Merge repository now correctly reproduces the maximally shrunk test case.
